// Real-time audio to UART packet bridge for CMOD A7 + INMP441
//
// Pipeline implemented:
// 1) I2S receive (24-bit left channel)
// 2) Decimate by 6 to ~7.812 kHz, convert to signed 16-bit
// 3) Accumulate mean absolute amplitude over 8-second windows
// 4) Build UART frame: 0xAA, 0x55, RESULT, RMS_ENERGY, FLAGS, SEQ, METRIC, CHECKSUM
//
// FFT/CNN are intentionally skipped for now. RESULT is generated by a
// placeholder detector based on mean amplitude threshold.
module recorder_top (
    input  wire clk,      // 12 MHz system clock
    input  wire btn0,     // Reserved for future use
    input  wire btn1,     // Reserved for future use
    input  wire i2s_sd,   // I2S serial data from INMP441
    output wire i2s_sck,  // I2S serial clock to INMP441
    output wire i2s_ws,   // I2S word select to INMP441
    output reg  led,      // Status LED (A17)
    output wire led_amp,  // Amplitude LED via PWM (C16)
    output wire uart_tx   // UART TX to ESP32 RX
);

    localparam DECIM            = 6;
    localparam WINDOW_SAMPLES   = 391;     // ~50ms @ 7812.5 Hz
    localparam AMP_SHIFT        = 5;       // scale mean_abs to 8-bit
    localparam ANOMALY_THRESHOLD = 16'd1800; // placeholder threshold

    // UART: 1,000,000 baud, 8N1 at 12 MHz
    localparam UART_BAUD        = 1_000_000;

    // ----------------------------------------------------------------
    // Power-on reset (8 clock cycles)
    // ----------------------------------------------------------------
    reg [3:0] rst_cnt = 4'd0;
    wire rst_n = rst_cnt[3];
    always @(posedge clk)
        if (!rst_n) rst_cnt <= rst_cnt + 4'd1;

    // ----------------------------------------------------------------
    // I2S receiver
    // ----------------------------------------------------------------
    wire [23:0] sample_data;
    wire        sample_valid;

    i2s_receiver i2s_inst (
        .clk          (clk),
        .rst_n        (rst_n),
        .i2s_sd       (i2s_sd),
        .i2s_sck      (i2s_sck),
        .i2s_ws       (i2s_ws),
        .sample_data  (sample_data),
        .sample_valid (sample_valid)
    );

    // ----------------------------------------------------------------
    // Decimator and sample shaping
    // ----------------------------------------------------------------
    reg  [2:0] decim_cnt = 3'd0;
    reg [15:0] sample_s16 = 16'd0;
    reg        sample_ena = 1'b0;

    wire [15:0] abs_sample = sample_s16[15] ? (~sample_s16 + 16'd1) : sample_s16;

    always @(posedge clk) begin
        sample_ena <= 1'b0;
        if (sample_valid) begin
            if (decim_cnt == DECIM - 1) begin
                decim_cnt  <= 3'd0;
                sample_s16 <= sample_data[23:8];
                sample_ena <= 1'b1;
            end else begin
                decim_cnt <= decim_cnt + 3'd1;
            end
        end
    end

    // ----------------------------------------------------------------
    // Window statistics: mean absolute amplitude over 8 seconds
    // ----------------------------------------------------------------
    reg [31:0] abs_sum       = 32'd0;
    reg [15:0] sample_count  = 16'd0;
    reg [31:0] mean_abs      = 32'd0;
    reg [7:0]  rms_energy    = 8'd0;
    reg        anomaly_result = 1'b0;
    wire [31:0] window_mean_calc = (abs_sum + abs_sample) / WINDOW_SAMPLES;

    // ----------------------------------------------------------------
    // Local amplitude LED (always live from real-time sample)
    // ----------------------------------------------------------------
    reg [7:0] pwm_cnt      = 8'd0;
    reg [7:0] live_amp_byte = 8'd0;
    always @(posedge clk) pwm_cnt <= pwm_cnt + 8'd1;
    assign led_amp = (pwm_cnt < live_amp_byte);

    // ----------------------------------------------------------------
    // UART packet FSM
    // Frame: 0xAA 0x55 RESULT RMS_ENERGY FLAGS SEQ METRIC CHECKSUM
    // ----------------------------------------------------------------
    reg        uart_start = 1'b0;
    reg [7:0]  uart_data  = 8'd0;
    wire       uart_busy;
    wire       uart_done;

    reg [3:0]  tx_state = 4'd0;
    reg [7:0]  tx_result = 8'd0;
    reg [7:0]  tx_rms    = 8'd0;
    reg [7:0]  tx_flags  = 8'd0;
    reg [7:0]  tx_seq    = 8'd0;
    reg [7:0]  tx_metric = 8'd0;
    reg [7:0]  tx_chk    = 8'd0;

    uart_tx #(
        .CLK_FREQ_HZ (12_000_000),
        .BAUD_RATE   (UART_BAUD)
    ) uart_tx_inst (
        .clk    (clk),
        .rst_n  (rst_n),
        .start  (uart_start),
        .data   (uart_data),
        .tx     (uart_tx),
        .busy   (uart_busy),
        .done   (uart_done)
    );

    always @(posedge clk) begin
        uart_start <= 1'b0;

        if (!rst_n) begin
            abs_sum        <= 32'd0;
            sample_count   <= 16'd0;
            mean_abs       <= 32'd0;
            rms_energy     <= 8'd0;
            anomaly_result <= 1'b0;
            live_amp_byte  <= 8'd0;
            led            <= 1'b0;
            tx_state       <= 4'd0;
            tx_result      <= 8'd0;
            tx_rms         <= 8'd0;
            tx_flags       <= 8'd0;
            tx_seq         <= 8'd0;
            tx_metric      <= 8'd0;
            tx_chk         <= 8'd0;
        end else begin
            // Running status LED heartbeat (slow blink)
            led <= pwm_cnt[7] ^ btn0;

            // btn1 clears current window accumulation immediately.
            if (btn1) begin
                abs_sum      <= 32'd0;
                sample_count <= 16'd0;
                live_amp_byte <= 8'd0;
            end

            // Live amplitude estimate for LED PWM
            if (sample_ena) begin
                if (abs_sample[15:8] != 8'd0)
                    live_amp_byte <= 8'hFF;
                else
                    live_amp_byte <= (abs_sample[7:0] << 1);
            end

            // 8-second stats window
            if (sample_ena) begin
                if (sample_count == WINDOW_SAMPLES - 1) begin
                    // Include this sample before finalizing window
                    mean_abs <= window_mean_calc;

                    if (window_mean_calc > ANOMALY_THRESHOLD)
                        anomaly_result <= 1'b1;
                    else
                        anomaly_result <= 1'b0;

                    // RMS byte scaling (mean absolute, shifted)
                    if ((window_mean_calc >> AMP_SHIFT) > 32'd255)
                        rms_energy <= 8'hFF;
                    else
                        rms_energy <= window_mean_calc[AMP_SHIFT+7:AMP_SHIFT];

                    abs_sum      <= 32'd0;
                    sample_count <= 16'd0;

                    // Use the freshly computed window values for this frame.
                    tx_result <= (window_mean_calc > ANOMALY_THRESHOLD) ? 8'd1 : 8'd0;
                    if ((window_mean_calc >> AMP_SHIFT) > 32'd255)
                        tx_rms <= 8'hFF;
                    else
                        tx_rms <= window_mean_calc[AMP_SHIFT+7:AMP_SHIFT];
                    // bit0=1 indicates FPGA active/awake; remaining bits reserved.
                    tx_flags <= 8'h01;
                    // Placeholder for future CNN confidence (0..255 for now).
                    tx_metric <= 8'd0;
                    tx_chk   <= 8'hAA ^ 8'h55
                                ^ ((window_mean_calc > ANOMALY_THRESHOLD) ? 8'd1 : 8'd0)
                                ^ (((window_mean_calc >> AMP_SHIFT) > 32'd255)
                                    ? 8'hFF
                                    : window_mean_calc[AMP_SHIFT+7:AMP_SHIFT])
                                ^ 8'h01
                                ^ tx_seq
                                ^ 8'd0;
                    if (tx_state == 4'd0)
                        tx_state <= 4'd1;
                end else begin
                    abs_sum      <= abs_sum + abs_sample;
                    sample_count <= sample_count + 16'd1;
                end
            end

            // UART frame send state machine
            case (tx_state)
                4'd0: begin
                    // Wait for next window to request a frame.
                end

                4'd1: begin
                    if (!uart_busy) begin
                        uart_data  <= 8'hAA;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd2;
                    end
                end

                4'd2: if (uart_done) tx_state <= 4'd3;

                4'd3: begin
                    if (!uart_busy) begin
                        uart_data  <= 8'h55;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd4;
                    end
                end

                4'd4: if (uart_done) tx_state <= 4'd5;

                4'd5: begin
                    if (!uart_busy) begin
                        uart_data  <= tx_result;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd6;
                    end
                end

                4'd6: if (uart_done) tx_state <= 4'd7;

                4'd7: begin
                    if (!uart_busy) begin
                        uart_data  <= tx_rms;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd8;
                    end
                end

                4'd8: if (uart_done) tx_state <= 4'd9;

                4'd9: begin
                    if (!uart_busy) begin
                        uart_data  <= tx_flags;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd10;
                    end
                end

                4'd10: if (uart_done) tx_state <= 4'd11;

                4'd11: begin
                    if (!uart_busy) begin
                        uart_data  <= tx_seq;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd12;
                    end
                end

                4'd12: if (uart_done) tx_state <= 4'd13;

                4'd13: begin
                    if (!uart_busy) begin
                        uart_data  <= tx_metric;
                        uart_start <= 1'b1;
                        tx_state   <= 4'd14;
                    end
                end

                4'd14: if (uart_done) tx_state <= 4'd15;

                4'd15: begin
                    if (uart_done) begin
                        // 8-bit increment naturally rolls over 255 -> 0.
                        tx_seq   <= tx_seq + 8'd1;
                        tx_state <= 4'd0;
                    end else if (!uart_busy) begin
                        uart_data  <= tx_chk;
                        uart_start <= 1'b1;
                    end
                end

                default: tx_state <= 4'd0;
            endcase
        end
    end

endmodule
