-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_4u_array_ap_ufixed_4_1_4_0_0_4u_relu_config12_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer10_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    layer10_out_empty_n : IN STD_LOGIC;
    layer10_out_read : OUT STD_LOGIC;
    layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    layer12_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer12_out_full_n : IN STD_LOGIC;
    layer12_out_write : OUT STD_LOGIC;
    layer12_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    layer12_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_4u_array_ap_ufixed_4_1_4_0_0_4u_relu_config12_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer10_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal layer12_out_blk_n : STD_LOGIC;
    signal out_data_fu_297_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_data_reg_806 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal out_data_1_fu_453_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_data_1_reg_811 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_data_2_fu_609_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_data_2_reg_816 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_data_3_fu_765_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_data_3_reg_821 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i1_fu_94 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal i_fu_773_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal trunc_ln44_fu_119_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_189_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_fu_177_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_fu_167_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln52_fu_203_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln52_fu_207_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_221_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_181_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_213_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_2_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_1_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_159_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_273_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln52_1_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_1_fu_281_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln51_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_2_fu_289_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln44_1_fu_123_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_345_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_329_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_2_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_1_fu_319_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln52_1_fu_359_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln52_1_fu_363_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_377_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_337_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_369_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_9_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_3_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_32_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_1_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_2_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_3_fu_429_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln52_3_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_4_fu_437_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln51_1_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_5_fu_445_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln44_2_fu_133_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_501_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_485_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_4_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_2_fu_475_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln52_2_fu_515_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln52_2_fu_519_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_15_fu_533_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_12_fu_493_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_525_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_16_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_5_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_33_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_467_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_2_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_4_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_6_fu_585_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln52_5_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_7_fu_593_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln51_2_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_8_fu_601_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln44_3_fu_143_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_657_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_6_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_3_fu_631_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln52_3_fu_671_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln52_3_fu_675_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_21_fu_689_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_18_fu_649_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_681_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_23_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_7_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_34_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_623_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_3_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_6_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_9_fu_741_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln52_7_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_10_fu_749_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln51_3_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_11_fu_757_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_121 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i1_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_121)) then
                i1_fu_94 <= i_fu_773_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_data_1_reg_811 <= out_data_1_fu_453_p3;
                out_data_2_reg_816 <= out_data_2_fu_609_p3;
                out_data_3_reg_821 <= out_data_3_fu_765_p3;
                out_data_reg_806 <= out_data_fu_297_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln52_1_fu_363_p2 <= std_logic_vector(unsigned(trunc_ln52_1_fu_319_p4) + unsigned(zext_ln52_1_fu_359_p1));
    add_ln52_2_fu_519_p2 <= std_logic_vector(unsigned(trunc_ln52_2_fu_475_p4) + unsigned(zext_ln52_2_fu_515_p1));
    add_ln52_3_fu_675_p2 <= std_logic_vector(unsigned(trunc_ln52_3_fu_631_p4) + unsigned(zext_ln52_3_fu_671_p1));
    add_ln52_fu_207_p2 <= std_logic_vector(unsigned(trunc_ln3_fu_167_p4) + unsigned(zext_ln52_fu_203_p1));
    and_ln52_1_fu_243_p2 <= (tmp_3_fu_213_p3 or not_tmp_2_fu_237_p2);
    and_ln52_2_fu_353_p2 <= (tmp_8_fu_345_p3 and tmp_6_fu_329_p3);
    and_ln52_3_fu_399_p2 <= (tmp_9_fu_369_p3 or not_tmp_9_fu_393_p2);
    and_ln52_4_fu_509_p2 <= (tmp_13_fu_501_p3 and tmp_11_fu_485_p3);
    and_ln52_5_fu_555_p2 <= (tmp_14_fu_525_p3 or not_tmp_16_fu_549_p2);
    and_ln52_6_fu_665_p2 <= (tmp_19_fu_657_p3 and tmp_17_fu_641_p3);
    and_ln52_7_fu_711_p2 <= (tmp_20_fu_681_p3 or not_tmp_23_fu_705_p2);
    and_ln52_fu_197_p2 <= (trunc_ln52_fu_177_p1 and tmp_2_fu_189_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, layer12_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((layer12_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, layer12_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((layer12_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1))));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, layer12_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((layer12_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, layer12_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((layer12_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1))));
    end process;


    ap_block_state1_pp0_stage0_iter0_grp1_assign_proc : process(layer10_out_empty_n, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0_grp1 <= ((ap_done_reg = ap_const_logic_1) or (layer10_out_empty_n = ap_const_logic_0));
    end process;


    ap_condition_121_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_121 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_779_p2, ap_start_int)
    begin
        if (((icmp_ln41_fu_779_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, i1_fu_94, ap_loop_init, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_94;
        end if; 
    end process;

    empty_32_fu_405_p2 <= (icmp_ln52_1_fu_387_p2 and and_ln52_3_fu_399_p2);
    empty_33_fu_561_p2 <= (icmp_ln52_2_fu_543_p2 and and_ln52_5_fu_555_p2);
    empty_34_fu_717_p2 <= (icmp_ln52_3_fu_699_p2 and and_ln52_7_fu_711_p2);
    empty_fu_249_p2 <= (icmp_ln52_fu_231_p2 and and_ln52_1_fu_243_p2);
    i_fu_773_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv8_1));
    icmp_ln41_fu_779_p2 <= "1" when (ap_sig_allocacmp_i1_load = ap_const_lv8_FF) else "0";
    icmp_ln51_1_fu_305_p2 <= "1" when (signed(trunc_ln44_1_fu_123_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln51_2_fu_461_p2 <= "1" when (signed(trunc_ln44_2_fu_133_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln51_3_fu_617_p2 <= "1" when (signed(trunc_ln44_3_fu_143_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln51_fu_153_p2 <= "1" when (signed(trunc_ln44_fu_119_p1) > signed(ap_const_lv8_0)) else "0";
    icmp_ln52_1_fu_387_p2 <= "1" when (tmp_s_fu_377_p4 = ap_const_lv3_0) else "0";
    icmp_ln52_2_fu_543_p2 <= "1" when (tmp_15_fu_533_p4 = ap_const_lv3_0) else "0";
    icmp_ln52_3_fu_699_p2 <= "1" when (tmp_21_fu_689_p4 = ap_const_lv3_0) else "0";
    icmp_ln52_fu_231_p2 <= "1" when (tmp_5_fu_221_p4 = ap_const_lv3_0) else "0";

    layer10_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, layer10_out_empty_n, ap_done_reg, ap_block_pp0_stage0_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_done_reg = ap_const_logic_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer10_out_blk_n <= layer10_out_empty_n;
        else 
            layer10_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer10_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer10_out_read <= ap_const_logic_1;
        else 
            layer10_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer12_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer12_out_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer12_out_blk_n <= layer12_out_full_n;
        else 
            layer12_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer12_out_din <= (((out_data_3_reg_821 & out_data_2_reg_816) & out_data_1_reg_811) & out_data_reg_806);

    layer12_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer12_out_write <= ap_const_logic_1;
        else 
            layer12_out_write <= ap_const_logic_0;
        end if; 
    end process;

    not_tmp_16_fu_549_p2 <= (tmp_12_fu_493_p3 xor ap_const_lv1_1);
    not_tmp_23_fu_705_p2 <= (tmp_18_fu_649_p3 xor ap_const_lv1_1);
    not_tmp_2_fu_237_p2 <= (tmp_1_fu_181_p3 xor ap_const_lv1_1);
    not_tmp_9_fu_393_p2 <= (tmp_7_fu_337_p3 xor ap_const_lv1_1);
    or_ln52_1_fu_267_p2 <= (xor_ln52_fu_261_p2 or tmp_fu_159_p3);
    or_ln52_2_fu_411_p2 <= (tmp_4_fu_311_p3 or empty_32_fu_405_p2);
    or_ln52_3_fu_423_p2 <= (xor_ln52_1_fu_417_p2 or tmp_4_fu_311_p3);
    or_ln52_4_fu_567_p2 <= (tmp_10_fu_467_p3 or empty_33_fu_561_p2);
    or_ln52_5_fu_579_p2 <= (xor_ln52_2_fu_573_p2 or tmp_10_fu_467_p3);
    or_ln52_6_fu_723_p2 <= (tmp_16_fu_623_p3 or empty_34_fu_717_p2);
    or_ln52_7_fu_735_p2 <= (xor_ln52_3_fu_729_p2 or tmp_16_fu_623_p3);
    or_ln52_fu_255_p2 <= (tmp_fu_159_p3 or empty_fu_249_p2);
    out_data_1_fu_453_p3 <= 
        select_ln52_5_fu_445_p3 when (icmp_ln51_1_fu_305_p2(0) = '1') else 
        ap_const_lv4_0;
    out_data_2_fu_609_p3 <= 
        select_ln52_8_fu_601_p3 when (icmp_ln51_2_fu_461_p2(0) = '1') else 
        ap_const_lv4_0;
    out_data_3_fu_765_p3 <= 
        select_ln52_11_fu_757_p3 when (icmp_ln51_3_fu_617_p2(0) = '1') else 
        ap_const_lv4_0;
    out_data_fu_297_p3 <= 
        select_ln52_2_fu_289_p3 when (icmp_ln51_fu_153_p2(0) = '1') else 
        ap_const_lv4_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln52_10_fu_749_p3 <= 
        select_ln52_9_fu_741_p3 when (or_ln52_6_fu_723_p2(0) = '1') else 
        ap_const_lv4_F;
    select_ln52_11_fu_757_p3 <= 
        select_ln52_10_fu_749_p3 when (or_ln52_7_fu_735_p2(0) = '1') else 
        add_ln52_3_fu_675_p2;
    select_ln52_1_fu_281_p3 <= 
        select_ln52_fu_273_p3 when (or_ln52_fu_255_p2(0) = '1') else 
        ap_const_lv4_F;
    select_ln52_2_fu_289_p3 <= 
        select_ln52_1_fu_281_p3 when (or_ln52_1_fu_267_p2(0) = '1') else 
        add_ln52_fu_207_p2;
    select_ln52_3_fu_429_p3 <= 
        ap_const_lv4_0 when (tmp_4_fu_311_p3(0) = '1') else 
        add_ln52_1_fu_363_p2;
    select_ln52_4_fu_437_p3 <= 
        select_ln52_3_fu_429_p3 when (or_ln52_2_fu_411_p2(0) = '1') else 
        ap_const_lv4_F;
    select_ln52_5_fu_445_p3 <= 
        select_ln52_4_fu_437_p3 when (or_ln52_3_fu_423_p2(0) = '1') else 
        add_ln52_1_fu_363_p2;
    select_ln52_6_fu_585_p3 <= 
        ap_const_lv4_0 when (tmp_10_fu_467_p3(0) = '1') else 
        add_ln52_2_fu_519_p2;
    select_ln52_7_fu_593_p3 <= 
        select_ln52_6_fu_585_p3 when (or_ln52_4_fu_567_p2(0) = '1') else 
        ap_const_lv4_F;
    select_ln52_8_fu_601_p3 <= 
        select_ln52_7_fu_593_p3 when (or_ln52_5_fu_579_p2(0) = '1') else 
        add_ln52_2_fu_519_p2;
    select_ln52_9_fu_741_p3 <= 
        ap_const_lv4_0 when (tmp_16_fu_623_p3(0) = '1') else 
        add_ln52_3_fu_675_p2;
    select_ln52_fu_273_p3 <= 
        ap_const_lv4_0 when (tmp_fu_159_p3(0) = '1') else 
        add_ln52_fu_207_p2;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_467_p3 <= layer10_out_dout(23 downto 23);
    tmp_11_fu_485_p3 <= layer10_out_dout(16 downto 16);
    tmp_12_fu_493_p3 <= layer10_out_dout(20 downto 20);
    tmp_13_fu_501_p3 <= layer10_out_dout(17 downto 17);
    tmp_14_fu_525_p3 <= add_ln52_2_fu_519_p2(3 downto 3);
    tmp_15_fu_533_p4 <= layer10_out_dout(23 downto 21);
    tmp_16_fu_623_p3 <= layer10_out_dout(31 downto 31);
    tmp_17_fu_641_p3 <= layer10_out_dout(24 downto 24);
    tmp_18_fu_649_p3 <= layer10_out_dout(28 downto 28);
    tmp_19_fu_657_p3 <= layer10_out_dout(25 downto 25);
    tmp_1_fu_181_p3 <= layer10_out_dout(4 downto 4);
    tmp_20_fu_681_p3 <= add_ln52_3_fu_675_p2(3 downto 3);
    tmp_21_fu_689_p4 <= layer10_out_dout(31 downto 29);
    tmp_2_fu_189_p3 <= layer10_out_dout(1 downto 1);
    tmp_3_fu_213_p3 <= add_ln52_fu_207_p2(3 downto 3);
    tmp_4_fu_311_p3 <= layer10_out_dout(15 downto 15);
    tmp_5_fu_221_p4 <= layer10_out_dout(7 downto 5);
    tmp_6_fu_329_p3 <= layer10_out_dout(8 downto 8);
    tmp_7_fu_337_p3 <= layer10_out_dout(12 downto 12);
    tmp_8_fu_345_p3 <= layer10_out_dout(9 downto 9);
    tmp_9_fu_369_p3 <= add_ln52_1_fu_363_p2(3 downto 3);
    tmp_fu_159_p3 <= layer10_out_dout(7 downto 7);
    tmp_s_fu_377_p4 <= layer10_out_dout(15 downto 13);
    trunc_ln3_fu_167_p4 <= layer10_out_dout(4 downto 1);
    trunc_ln44_1_fu_123_p4 <= layer10_out_dout(15 downto 8);
    trunc_ln44_2_fu_133_p4 <= layer10_out_dout(23 downto 16);
    trunc_ln44_3_fu_143_p4 <= layer10_out_dout(31 downto 24);
    trunc_ln44_fu_119_p1 <= layer10_out_dout(8 - 1 downto 0);
    trunc_ln52_1_fu_319_p4 <= layer10_out_dout(12 downto 9);
    trunc_ln52_2_fu_475_p4 <= layer10_out_dout(20 downto 17);
    trunc_ln52_3_fu_631_p4 <= layer10_out_dout(28 downto 25);
    trunc_ln52_fu_177_p1 <= layer10_out_dout(1 - 1 downto 0);
    xor_ln52_1_fu_417_p2 <= (empty_32_fu_405_p2 xor ap_const_lv1_1);
    xor_ln52_2_fu_573_p2 <= (empty_33_fu_561_p2 xor ap_const_lv1_1);
    xor_ln52_3_fu_729_p2 <= (empty_34_fu_717_p2 xor ap_const_lv1_1);
    xor_ln52_fu_261_p2 <= (empty_fu_249_p2 xor ap_const_lv1_1);
    zext_ln52_1_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln52_2_fu_353_p2),4));
    zext_ln52_2_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln52_4_fu_509_p2),4));
    zext_ln52_3_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln52_6_fu_665_p2),4));
    zext_ln52_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln52_fu_197_p2),4));
end behav;
