// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer8_out_dout,
        layer8_out_empty_n,
        layer8_out_read,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer9_out_din,
        layer9_out_full_n,
        layer9_out_write,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] layer8_out_dout;
input   layer8_out_empty_n;
output   layer8_out_read;
input  [10:0] layer8_out_num_data_valid;
input  [10:0] layer8_out_fifo_cap;
output  [63:0] layer9_out_din;
input   layer9_out_full_n;
output   layer9_out_write;
input  [8:0] layer9_out_num_data_valid;
input  [8:0] layer9_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer8_out_read;
reg layer9_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln55_reg_907;
reg   [0:0] and_ln55_1_reg_911;
reg    ap_predicate_op136_write_state4;
reg    ap_block_state4_pp0_stage1_iter1_grp2;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg   [0:0] icmp_ln109_reg_903;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY_1;
reg   [31:0] pY_1;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap;
reg   [31:0] pX_1;
reg   [31:0] sX_1;
reg    layer8_out_blk_n;
wire    ap_block_pp0_stage1_grp1;
reg    layer9_out_blk_n;
wire    ap_block_pp0_stage1_grp2;
wire   [0:0] icmp_ln109_fu_204_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln55_fu_257_p2;
wire   [0:0] and_ln55_1_fu_299_p2;
wire   [8:0] select_ln65_fu_405_p3;
reg   [8:0] select_ln65_reg_915;
wire   [8:0] select_ln65_1_fu_513_p3;
reg   [8:0] select_ln65_1_reg_920;
wire   [8:0] select_ln65_2_fu_621_p3;
reg   [8:0] select_ln65_2_reg_925;
wire   [8:0] select_ln65_3_fu_729_p3;
reg   [8:0] select_ln65_3_reg_930;
wire   [0:0] icmp_ln76_fu_743_p2;
reg   [0:0] icmp_ln76_reg_935;
wire   [0:0] icmp_ln80_fu_797_p2;
wire   [31:0] select_ln86_fu_825_p3;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_done;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_idle;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ready;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read1;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read2;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read3;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld;
wire   [5:0] call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4;
wire    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld;
reg    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce;
reg    ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2;
reg    ap_block_pp0_stage1_11001_ignoreCallOp22;
reg    ap_block_pp0_stage1_11001_ignoreCallOp22_grp1;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_131;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_i_reg_131;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg;
wire    ap_block_pp0_stage1_ignoreCallOp22_grp1;
wire    ap_block_pp0_stage0;
wire   [31:0] add_ln80_fu_791_p2;
wire   [31:0] add_ln76_fu_737_p2;
wire   [31:0] select_ln91_fu_761_p3;
reg   [9:0] indvar_flatten2_fu_114;
wire   [9:0] add_ln109_fu_198_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_indvar_flatten2_load;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage1_01001_grp2;
reg    ap_block_pp0_stage1_11001_grp2;
wire   [0:0] icmp_ln55_2_fu_281_p2;
wire   [0:0] icmp_ln55_3_fu_287_p2;
wire   [0:0] and_ln55_fu_293_p2;
wire   [0:0] icmp_ln55_1_fu_271_p2;
wire   [8:0] shl_ln_fu_309_p3;
wire   [8:0] shl_ln63_s_fu_321_p3;
wire   [0:0] icmp_ln65_fu_353_p2;
wire   [0:0] xor_ln65_fu_359_p2;
wire   [8:0] shl_ln63_1_fu_333_p3;
wire   [8:0] shl_ln63_2_fu_345_p3;
wire   [0:0] icmp_ln65_1_fu_373_p2;
wire   [0:0] xor_ln65_1_fu_379_p2;
wire   [8:0] select_ln0_fu_365_p3;
wire   [8:0] select_ln0_1_fu_385_p3;
wire   [0:0] icmp_ln65_2_fu_393_p2;
wire   [0:0] xor_ln65_2_fu_399_p2;
wire   [8:0] shl_ln63_3_fu_417_p3;
wire   [8:0] shl_ln63_4_fu_429_p3;
wire   [0:0] icmp_ln65_3_fu_461_p2;
wire   [0:0] xor_ln65_3_fu_467_p2;
wire   [8:0] shl_ln63_5_fu_441_p3;
wire   [8:0] shl_ln63_6_fu_453_p3;
wire   [0:0] icmp_ln65_4_fu_481_p2;
wire   [0:0] xor_ln65_4_fu_487_p2;
wire   [8:0] select_ln0_2_fu_473_p3;
wire   [8:0] select_ln0_3_fu_493_p3;
wire   [0:0] icmp_ln65_5_fu_501_p2;
wire   [0:0] xor_ln65_5_fu_507_p2;
wire   [8:0] shl_ln63_7_fu_525_p3;
wire   [8:0] shl_ln63_8_fu_537_p3;
wire   [0:0] icmp_ln65_6_fu_569_p2;
wire   [0:0] xor_ln65_6_fu_575_p2;
wire   [8:0] shl_ln63_9_fu_549_p3;
wire   [8:0] shl_ln63_10_fu_561_p3;
wire   [0:0] icmp_ln65_7_fu_589_p2;
wire   [0:0] xor_ln65_7_fu_595_p2;
wire   [8:0] select_ln0_4_fu_581_p3;
wire   [8:0] select_ln0_5_fu_601_p3;
wire   [0:0] icmp_ln65_8_fu_609_p2;
wire   [0:0] xor_ln65_8_fu_615_p2;
wire   [8:0] shl_ln63_11_fu_633_p3;
wire   [8:0] shl_ln63_12_fu_645_p3;
wire   [0:0] icmp_ln65_9_fu_677_p2;
wire   [0:0] xor_ln65_9_fu_683_p2;
wire   [8:0] shl_ln63_13_fu_657_p3;
wire   [8:0] shl_ln63_14_fu_669_p3;
wire   [0:0] icmp_ln65_10_fu_697_p2;
wire   [0:0] xor_ln65_10_fu_703_p2;
wire   [8:0] select_ln0_6_fu_689_p3;
wire   [8:0] select_ln0_7_fu_709_p3;
wire   [0:0] icmp_ln65_11_fu_717_p2;
wire   [0:0] xor_ln65_11_fu_723_p2;
wire   [31:0] add_ln91_fu_755_p2;
wire   [0:0] icmp_ln86_fu_813_p2;
wire   [31:0] add_ln86_fu_819_p2;
wire   [10:0] res_pack_fu_839_p3;
wire   [10:0] res_pack_1_fu_850_p3;
wire   [10:0] res_pack_2_fu_861_p3;
wire   [15:0] zext_ln48_2_fu_868_p1;
wire   [15:0] zext_ln48_1_fu_857_p1;
wire   [15:0] zext_ln48_fu_846_p1;
wire   [58:0] or_ln72_s_fu_872_p6;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage1_11001;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_266;
reg    ap_condition_252;
reg    ap_condition_365;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 sY_1 = 32'd0;
#0 pY_1 = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap = 6'd0;
#0 pX_1 = 32'd0;
#0 sX_1 = 32'd0;
#0 ap_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg = 1'b0;
#0 indvar_flatten2_fu_114 = 10'd0;
end

myproject_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start),
    .ap_done(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_done),
    .ap_idle(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_idle),
    .ap_ready(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ready),
    .p_read(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read),
    .p_read1(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read1),
    .p_read2(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read2),
    .p_read3(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read3),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld),
    .ap_ce(call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg <= 1'b1;
        end else if ((call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ready == 1'b1)) begin
            call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage1_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln80_fu_797_p2 == 1'd1) & (icmp_ln76_fu_743_p2 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_storemerge_i_reg_131 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln80_fu_797_p2 == 1'd0) & (icmp_ln76_fu_743_p2 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_storemerge_i_reg_131 <= select_ln86_fu_825_p3;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_storemerge_i_reg_131 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_131;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        indvar_flatten2_fu_114 <= add_ln109_fu_198_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_252)) begin
    if ((icmp_ln76_fu_743_p2 == 1'd1)) begin
        pX_1 <= 32'd0;
    end else if ((icmp_ln76_fu_743_p2 == 1'd0)) begin
        pX_1 <= add_ln76_fu_737_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_365)) begin
    if ((icmp_ln80_fu_797_p2 == 1'd1)) begin
        pY_1 <= 32'd0;
    end else if ((icmp_ln80_fu_797_p2 == 1'd0)) begin
        pY_1 <= add_ln80_fu_791_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_252)) begin
    if ((icmp_ln76_fu_743_p2 == 1'd1)) begin
        sX_1 <= 32'd0;
    end else if ((icmp_ln76_fu_743_p2 == 1'd0)) begin
        sX_1 <= select_ln91_fu_761_p3;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_1_reg_911 <= and_ln55_1_fu_299_p2;
        icmp_ln109_reg_903 <= icmp_ln109_fu_204_p2;
        icmp_ln55_reg_907 <= icmp_ln55_fu_257_p2;
        icmp_ln76_reg_935 <= icmp_ln76_fu_743_p2;
        select_ln65_1_reg_920[8 : 3] <= select_ln65_1_fu_513_p3[8 : 3];
        select_ln65_2_reg_925[8 : 3] <= select_ln65_2_fu_621_p3[8 : 3];
        select_ln65_3_reg_930[8 : 3] <= select_ln65_3_fu_729_p3[8 : 3];
        select_ln65_reg_915[8 : 3] <= select_ln65_fu_405_p3[8 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln76_reg_935 == 1'd1))) begin
        sY_1 <= ap_phi_reg_pp0_iter1_storemerge_i_reg_131;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_903 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp22_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce = 1'b1;
    end else begin
        call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op136_write_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage1_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op136_write_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_198_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 10'd1);

assign add_ln76_fu_737_p2 = (pX_1 + 32'd1);

assign add_ln80_fu_791_p2 = (pY_1 + 32'd1);

assign add_ln86_fu_819_p2 = (sY_1 + 32'd1);

assign add_ln91_fu_755_p2 = (sX_1 + 32'd1);

assign and_ln55_1_fu_299_p2 = (icmp_ln55_1_fu_271_p2 & and_ln55_fu_293_p2);

assign and_ln55_fu_293_p2 = (icmp_ln55_3_fu_287_p2 & icmp_ln55_2_fu_281_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (layer8_out_empty_n == 1'b0)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (layer8_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp22 = (((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (layer8_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp22_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (layer8_out_empty_n == 1'b0));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp22_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (layer8_out_empty_n == 1'b0)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (layer8_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp2));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state4_pp0_stage1_iter1_grp2 = ((ap_predicate_op136_write_state4 == 1'b1) & (layer9_out_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2 = ((ap_predicate_op136_write_state4 == 1'b1) & (layer9_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_252 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_266 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_365 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_743_p2 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_storemerge_i_reg_131 = 'bx;

always @ (*) begin
    ap_predicate_op136_write_state4 = ((1'd1 == and_ln55_1_reg_911) & (icmp_ln55_reg_907 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start = call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg;

assign call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read = layer8_out_dout[5:0];

assign call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read1 = {{layer8_out_dout[11:6]}};

assign call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read2 = {{layer8_out_dout[17:12]}};

assign call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read3 = {{layer8_out_dout[23:18]}};

assign icmp_ln109_fu_204_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 10'd1023) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_271_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_281_p2 = (($signed(pY_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_287_p2 = (($signed(pX_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_257_p2 = ((sX_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln65_10_fu_697_p2 = ((shl_ln63_13_fu_657_p3 < shl_ln63_14_fu_669_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_11_fu_717_p2 = ((select_ln0_6_fu_689_p3 < select_ln0_7_fu_709_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_373_p2 = ((shl_ln63_1_fu_333_p3 < shl_ln63_2_fu_345_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_393_p2 = ((select_ln0_fu_365_p3 < select_ln0_1_fu_385_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_3_fu_461_p2 = ((shl_ln63_3_fu_417_p3 < shl_ln63_4_fu_429_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_4_fu_481_p2 = ((shl_ln63_5_fu_441_p3 < shl_ln63_6_fu_453_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_5_fu_501_p2 = ((select_ln0_2_fu_473_p3 < select_ln0_3_fu_493_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_6_fu_569_p2 = ((shl_ln63_7_fu_525_p3 < shl_ln63_8_fu_537_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_7_fu_589_p2 = ((shl_ln63_9_fu_549_p3 < shl_ln63_10_fu_561_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_8_fu_609_p2 = ((select_ln0_4_fu_581_p3 < select_ln0_5_fu_601_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_9_fu_677_p2 = ((shl_ln63_11_fu_633_p3 < shl_ln63_12_fu_645_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_353_p2 = ((shl_ln_fu_309_p3 < shl_ln63_s_fu_321_p3) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_743_p2 = ((add_ln76_fu_737_p2 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_797_p2 = ((add_ln80_fu_791_p2 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_813_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign layer9_out_din = or_ln72_s_fu_872_p6;

assign or_ln72_s_fu_872_p6 = {{{{{select_ln65_3_reg_930}, {2'd0}}, {zext_ln48_2_fu_868_p1}}, {zext_ln48_1_fu_857_p1}}, {zext_ln48_fu_846_p1}};

assign res_pack_1_fu_850_p3 = {{select_ln65_1_reg_920}, {2'd0}};

assign res_pack_2_fu_861_p3 = {{select_ln65_2_reg_925}, {2'd0}};

assign res_pack_fu_839_p3 = {{select_ln65_reg_915}, {2'd0}};

assign select_ln0_1_fu_385_p3 = ((xor_ln65_1_fu_379_p2[0:0] == 1'b1) ? shl_ln63_1_fu_333_p3 : shl_ln63_2_fu_345_p3);

assign select_ln0_2_fu_473_p3 = ((xor_ln65_3_fu_467_p2[0:0] == 1'b1) ? shl_ln63_3_fu_417_p3 : shl_ln63_4_fu_429_p3);

assign select_ln0_3_fu_493_p3 = ((xor_ln65_4_fu_487_p2[0:0] == 1'b1) ? shl_ln63_5_fu_441_p3 : shl_ln63_6_fu_453_p3);

assign select_ln0_4_fu_581_p3 = ((xor_ln65_6_fu_575_p2[0:0] == 1'b1) ? shl_ln63_7_fu_525_p3 : shl_ln63_8_fu_537_p3);

assign select_ln0_5_fu_601_p3 = ((xor_ln65_7_fu_595_p2[0:0] == 1'b1) ? shl_ln63_9_fu_549_p3 : shl_ln63_10_fu_561_p3);

assign select_ln0_6_fu_689_p3 = ((xor_ln65_9_fu_683_p2[0:0] == 1'b1) ? shl_ln63_11_fu_633_p3 : shl_ln63_12_fu_645_p3);

assign select_ln0_7_fu_709_p3 = ((xor_ln65_10_fu_703_p2[0:0] == 1'b1) ? shl_ln63_13_fu_657_p3 : shl_ln63_14_fu_669_p3);

assign select_ln0_fu_365_p3 = ((xor_ln65_fu_359_p2[0:0] == 1'b1) ? shl_ln_fu_309_p3 : shl_ln63_s_fu_321_p3);

assign select_ln65_1_fu_513_p3 = ((xor_ln65_5_fu_507_p2[0:0] == 1'b1) ? select_ln0_2_fu_473_p3 : select_ln0_3_fu_493_p3);

assign select_ln65_2_fu_621_p3 = ((xor_ln65_8_fu_615_p2[0:0] == 1'b1) ? select_ln0_4_fu_581_p3 : select_ln0_5_fu_601_p3);

assign select_ln65_3_fu_729_p3 = ((xor_ln65_11_fu_723_p2[0:0] == 1'b1) ? select_ln0_6_fu_689_p3 : select_ln0_7_fu_709_p3);

assign select_ln65_fu_405_p3 = ((xor_ln65_2_fu_399_p2[0:0] == 1'b1) ? select_ln0_fu_365_p3 : select_ln0_1_fu_385_p3);

assign select_ln86_fu_825_p3 = ((icmp_ln86_fu_813_p2[0:0] == 1'b1) ? 32'd0 : add_ln86_fu_819_p2);

assign select_ln91_fu_761_p3 = ((icmp_ln55_fu_257_p2[0:0] == 1'b1) ? 32'd0 : add_ln91_fu_755_p2);

assign shl_ln63_10_fu_561_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1}, {3'd0}};

assign shl_ln63_11_fu_633_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16}, {3'd0}};

assign shl_ln63_12_fu_645_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12}, {3'd0}};

assign shl_ln63_13_fu_657_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4}, {3'd0}};

assign shl_ln63_14_fu_669_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap}, {3'd0}};

assign shl_ln63_1_fu_333_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11}, {3'd0}};

assign shl_ln63_2_fu_345_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3}, {3'd0}};

assign shl_ln63_3_fu_417_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18}, {3'd0}};

assign shl_ln63_4_fu_429_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14}, {3'd0}};

assign shl_ln63_5_fu_441_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10}, {3'd0}};

assign shl_ln63_6_fu_453_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2}, {3'd0}};

assign shl_ln63_7_fu_525_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17}, {3'd0}};

assign shl_ln63_8_fu_537_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13}, {3'd0}};

assign shl_ln63_9_fu_549_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5}, {3'd0}};

assign shl_ln63_s_fu_321_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15}, {3'd0}};

assign shl_ln_fu_309_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19}, {3'd0}};

assign start_out = real_start;

assign xor_ln65_10_fu_703_p2 = (icmp_ln65_10_fu_697_p2 ^ 1'd1);

assign xor_ln65_11_fu_723_p2 = (icmp_ln65_11_fu_717_p2 ^ 1'd1);

assign xor_ln65_1_fu_379_p2 = (icmp_ln65_1_fu_373_p2 ^ 1'd1);

assign xor_ln65_2_fu_399_p2 = (icmp_ln65_2_fu_393_p2 ^ 1'd1);

assign xor_ln65_3_fu_467_p2 = (icmp_ln65_3_fu_461_p2 ^ 1'd1);

assign xor_ln65_4_fu_487_p2 = (icmp_ln65_4_fu_481_p2 ^ 1'd1);

assign xor_ln65_5_fu_507_p2 = (icmp_ln65_5_fu_501_p2 ^ 1'd1);

assign xor_ln65_6_fu_575_p2 = (icmp_ln65_6_fu_569_p2 ^ 1'd1);

assign xor_ln65_7_fu_595_p2 = (icmp_ln65_7_fu_589_p2 ^ 1'd1);

assign xor_ln65_8_fu_615_p2 = (icmp_ln65_8_fu_609_p2 ^ 1'd1);

assign xor_ln65_9_fu_683_p2 = (icmp_ln65_9_fu_677_p2 ^ 1'd1);

assign xor_ln65_fu_359_p2 = (icmp_ln65_fu_353_p2 ^ 1'd1);

assign zext_ln48_1_fu_857_p1 = res_pack_1_fu_850_p3;

assign zext_ln48_2_fu_868_p1 = res_pack_2_fu_861_p3;

assign zext_ln48_fu_846_p1 = res_pack_fu_839_p3;

always @ (posedge ap_clk) begin
    select_ln65_reg_915[2:0] <= 3'b000;
    select_ln65_1_reg_920[2:0] <= 3'b000;
    select_ln65_2_reg_925[2:0] <= 3'b000;
    select_ln65_3_reg_930[2:0] <= 3'b000;
end

endmodule //myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s
