// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_fixed_16_6_5_3_0_4u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer17_out_dout,
        layer17_out_empty_n,
        layer17_out_read,
        layer17_out_num_data_valid,
        layer17_out_fifo_cap,
        layer2_out_din,
        layer2_out_full_n,
        layer2_out_write,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state7 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] layer17_out_dout;
input   layer17_out_empty_n;
output   layer17_out_read;
input  [13:0] layer17_out_num_data_valid;
input  [13:0] layer17_out_fifo_cap;
output  [63:0] layer2_out_din;
input   layer2_out_full_n;
output   layer2_out_write;
input  [12:0] layer2_out_num_data_valid;
input  [12:0] layer2_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer17_out_read;
reg layer2_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
reg   [31:0] sX_2;
reg   [31:0] pX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
wire   [5:0] outidx_i_i_i_i_address0;
wire   [1:0] outidx_i_i_i_i_q0;
wire   [5:0] w2_address0;
wire  signed [7:0] w2_q0;
reg    layer17_out_blk_n;
wire    ap_CS_fsm_state2;
reg    layer2_out_blk_n;
wire    ap_CS_fsm_state7;
reg   [0:0] icmp_ln289_reg_748;
reg   [0:0] and_ln289_1_reg_761;
reg   [3:0] in_index19_reg_199;
reg   [5:0] ir18_reg_210;
reg   [15:0] acc16_reg_221;
reg   [15:0] acc_114_reg_232;
reg   [15:0] acc_212_reg_243;
reg   [15:0] acc_311_reg_254;
wire   [0:0] icmp_ln289_fu_321_p2;
wire    ap_CS_fsm_state3;
wire   [12:0] add_ln51_fu_331_p2;
reg   [12:0] add_ln51_reg_756;
wire   [0:0] and_ln289_1_fu_375_p2;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_73_reg_765;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_74_reg_770;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_75_reg_775;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_76_reg_780;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_77_reg_785;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_78_reg_790;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_79_reg_795;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_80_reg_800;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_81_reg_805;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] a_fu_423_p21;
reg   [7:0] a_reg_815;
wire   [3:0] in_index_fu_470_p3;
reg   [3:0] in_index_reg_825;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] ir_fu_478_p2;
reg   [5:0] ir_reg_830;
wire   [0:0] icmp_ln124_fu_484_p2;
reg   [0:0] icmp_ln124_reg_835;
reg   [0:0] icmp_ln124_reg_835_pp0_iter1_reg;
reg   [1:0] out_index_reg_839;
reg   [11:0] trunc_ln_reg_847;
wire   [15:0] acc_8_fu_606_p3;
reg   [15:0] acc_8_reg_852;
reg    ap_enable_reg_pp0_iter2;
wire   [15:0] acc_7_fu_614_p3;
reg   [15:0] acc_7_reg_858;
wire   [15:0] acc_6_fu_622_p3;
reg   [15:0] acc_6_reg_864;
wire   [15:0] acc_fu_630_p3;
reg   [15:0] acc_reg_870;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_start;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_done;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_idle;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_ready;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld;
wire   [7:0] call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
wire    call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld;
reg   [12:0] indvar_flatten20_reg_187;
reg    ap_block_state1;
reg    ap_predicate_op87_write_state7;
reg    ap_block_state7;
wire   [0:0] icmp_ln51_fu_739_p2;
reg   [3:0] ap_phi_mux_in_index19_phi_fu_203_p4;
wire    ap_block_pp0_stage0;
reg   [5:0] ap_phi_mux_ir18_phi_fu_214_p4;
wire   [31:0] select_ln323_fu_718_p3;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_268_p4;
wire   [0:0] icmp_ln313_fu_652_p2;
wire   [0:0] icmp_ln317_fu_700_p2;
wire   [63:0] zext_ln124_fu_417_p1;
wire   [31:0] select_ln328_fu_669_p3;
wire   [31:0] add_ln313_fu_647_p2;
wire   [31:0] add_ln317_fu_694_p2;
reg    outidx_i_i_i_i_ce0_local;
reg    w2_ce0_local;
wire   [30:0] tmp_fu_337_p4;
wire   [30:0] tmp_26_fu_353_p4;
wire   [0:0] icmp_ln289_4_fu_347_p2;
wire   [0:0] icmp_ln289_5_fu_363_p2;
wire   [0:0] and_ln289_fu_369_p2;
wire   [0:0] grp_fu_307_p2;
wire   [7:0] a_fu_423_p19;
wire   [3:0] in_index_1_fu_458_p2;
wire   [0:0] icmp_ln141_fu_464_p2;
wire   [7:0] mul_ln73_fu_497_p1;
wire   [15:0] mul_ln73_fu_497_p2;
wire   [15:0] tmp_s_fu_513_p9;
wire   [15:0] tmp_s_fu_513_p11;
wire  signed [16:0] sext_ln133_fu_536_p1;
wire  signed [16:0] sext_ln133_1_fu_540_p1;
wire   [16:0] add_ln133_fu_543_p2;
wire   [0:0] icmp_ln133_1_fu_554_p2;
wire   [0:0] icmp_ln133_2_fu_559_p2;
wire   [0:0] or_ln133_1_fu_570_p2;
wire   [0:0] icmp_ln133_fu_549_p2;
wire   [0:0] or_ln133_fu_576_p2;
wire   [0:0] icmp_ln133_3_fu_564_p2;
wire   [0:0] or_ln133_2_fu_582_p2;
wire   [0:0] or_ln133_3_fu_600_p2;
wire   [15:0] acc_4_fu_588_p3;
wire   [15:0] acc_5_fu_596_p1;
wire   [31:0] add_ln328_fu_664_p2;
wire   [31:0] add_ln323_fu_712_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [15:0] mul_ln73_fu_497_p10;
reg    ap_condition_329;
wire   [3:0] a_fu_423_p1;
wire   [3:0] a_fu_423_p3;
wire   [3:0] a_fu_423_p5;
wire   [3:0] a_fu_423_p7;
wire   [3:0] a_fu_423_p9;
wire   [3:0] a_fu_423_p11;
wire   [3:0] a_fu_423_p13;
wire   [3:0] a_fu_423_p15;
wire  signed [3:0] a_fu_423_p17;
wire   [1:0] tmp_s_fu_513_p1;
wire   [1:0] tmp_s_fu_513_p3;
wire  signed [1:0] tmp_s_fu_513_p5;
wire  signed [1:0] tmp_s_fu_513_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig = 8'd0;
#0 sX_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_fixed_16_6_5_3_0_4u_config2_s_outidx_idEe #(
    .DataWidth( 2 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
outidx_i_i_i_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_i_i_i_i_address0),
    .ce0(outidx_i_i_i_i_ce0_local),
    .q0(outidx_i_i_i_i_q0)
);

myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_fixed_16_6_5_3_0_4u_config2_s_w2_ROM_AeOg #(
    .DataWidth( 8 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
w2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_address0),
    .ce0(w2_ce0_local),
    .q0(w2_q0)
);

myproject_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_start),
    .ap_done(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_done),
    .ap_idle(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_idle),
    .ap_ready(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_ready),
    .in_elem_0_0_0_0_0_val(layer17_out_dout),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld(call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_19_4_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 8 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
sparsemux_19_4_8_1_1_U19(
    .din0(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_73_reg_765),
    .din1(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_74_reg_770),
    .din2(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_75_reg_775),
    .din3(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_76_reg_780),
    .din4(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_77_reg_785),
    .din5(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_78_reg_790),
    .din6(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_79_reg_795),
    .din7(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_80_reg_800),
    .din8(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_81_reg_805),
    .def(a_fu_423_p19),
    .sel(ap_phi_mux_in_index19_phi_fu_203_p4),
    .dout(a_fu_423_p21)
);

myproject_mul_8s_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8ns_16_1_1_U20(
    .din0(w2_q0),
    .din1(mul_ln73_fu_497_p1),
    .dout(mul_ln73_fu_497_p2)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U21(
    .din0(acc16_reg_221),
    .din1(acc_114_reg_232),
    .din2(acc_212_reg_243),
    .din3(acc_311_reg_254),
    .def(tmp_s_fu_513_p9),
    .sel(out_index_reg_839),
    .dout(tmp_s_fu_513_p11)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln51_fu_739_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln124_reg_835_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc16_reg_221 <= acc_fu_630_p3;
    end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
        acc16_reg_221 <= 16'd65472;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln124_reg_835_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_114_reg_232 <= acc_6_fu_622_p3;
    end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
        acc_114_reg_232 <= 16'd65488;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln124_reg_835_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_212_reg_243 <= acc_7_fu_614_p3;
    end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
        acc_212_reg_243 <= 16'd65456;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln124_reg_835_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_311_reg_254 <= acc_8_fu_606_p3;
    end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
        acc_311_reg_254 <= 16'd64;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln124_reg_835 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_index19_reg_199 <= in_index_reg_825;
    end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
        in_index19_reg_199 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        indvar_flatten20_reg_187 <= add_ln51_reg_756;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        indvar_flatten20_reg_187 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln124_reg_835 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ir18_reg_210 <= ir_reg_830;
    end else if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
        ir18_reg_210 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        if ((icmp_ln313_fu_652_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln313_fu_652_p2 == 1'd0)) begin
            pX_2 <= add_ln313_fu_647_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln317_fu_700_p2 == 1'd1)) begin
            pY_2 <= 32'd0;
        end else if ((icmp_ln317_fu_700_p2 == 1'd0)) begin
            pY_2 <= add_ln317_fu_694_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        if ((icmp_ln313_fu_652_p2 == 1'd1)) begin
            sX_2 <= 32'd0;
        end else if ((icmp_ln313_fu_652_p2 == 1'd0)) begin
            sX_2 <= select_ln328_fu_669_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_reg_815 <= a_fu_423_p21;
        icmp_ln124_reg_835 <= icmp_ln124_fu_484_p2;
        icmp_ln124_reg_835_pp0_iter1_reg <= icmp_ln124_reg_835;
        out_index_reg_839 <= outidx_i_i_i_i_q0;
        trunc_ln_reg_847 <= {{mul_ln73_fu_497_p2[15:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_6_reg_864 <= acc_6_fu_622_p3;
        acc_7_reg_858 <= acc_7_fu_614_p3;
        acc_8_reg_852 <= acc_8_fu_606_p3;
        acc_reg_870 <= acc_fu_630_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln51_reg_756 <= add_ln51_fu_331_p2;
        and_ln289_1_reg_761 <= and_ln289_1_fu_375_p2;
        icmp_ln289_reg_748 <= icmp_ln289_fu_321_p2;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_73_reg_765 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_74_reg_770 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_75_reg_775 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_76_reg_780 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_77_reg_785 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_78_reg_790 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_79_reg_795 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_80_reg_800 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_81_reg_805 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_index_reg_825 <= in_index_fu_470_p3;
        ir_reg_830 <= ir_fu_478_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln313_fu_652_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        sY_2 <= ap_phi_mux_storemerge_i_i_phi_fu_268_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer17_out_empty_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state7)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln124_fu_484_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_739_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln124_reg_835 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_in_index19_phi_fu_203_p4 = in_index_reg_825;
    end else begin
        ap_phi_mux_in_index19_phi_fu_203_p4 = in_index19_reg_199;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln124_reg_835 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_ir18_phi_fu_214_p4 = ir_reg_830;
    end else begin
        ap_phi_mux_ir18_phi_fu_214_p4 = ir18_reg_210;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_652_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        if ((icmp_ln317_fu_700_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_268_p4 = 32'd0;
        end else if ((icmp_ln317_fu_700_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_268_p4 = select_ln323_fu_718_p3;
        end else begin
            ap_phi_mux_storemerge_i_i_phi_fu_268_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_268_p4 = 'bx;
    end
end

always @ (*) begin
    if (((layer17_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_start = 1'b1;
    end else begin
        call_ln286_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_275_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_739_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer17_out_blk_n = layer17_out_empty_n;
    end else begin
        layer17_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer17_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer17_out_read = 1'b1;
    end else begin
        layer17_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln289_1_reg_761) & (icmp_ln289_reg_748 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op87_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outidx_i_i_i_i_ce0_local = 1'b1;
    end else begin
        outidx_i_i_i_i_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_ce0_local = 1'b1;
    end else begin
        w2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer17_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'd1 == and_ln289_1_fu_375_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln289_fu_321_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln51_fu_739_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln51_fu_739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_423_p19 = 'bx;

assign acc_4_fu_588_p3 = ((or_ln133_2_fu_582_p2[0:0] == 1'b1) ? acc_311_reg_254 : 16'd0);

assign acc_5_fu_596_p1 = add_ln133_fu_543_p2[15:0];

assign acc_6_fu_622_p3 = ((icmp_ln133_1_fu_554_p2[0:0] == 1'b1) ? acc_5_fu_596_p1 : acc_114_reg_232);

assign acc_7_fu_614_p3 = ((icmp_ln133_2_fu_559_p2[0:0] == 1'b1) ? acc_5_fu_596_p1 : acc_212_reg_243);

assign acc_8_fu_606_p3 = ((or_ln133_3_fu_600_p2[0:0] == 1'b1) ? acc_4_fu_588_p3 : acc_5_fu_596_p1);

assign acc_fu_630_p3 = ((icmp_ln133_fu_549_p2[0:0] == 1'b1) ? acc_5_fu_596_p1 : acc16_reg_221);

assign add_ln133_fu_543_p2 = ($signed(sext_ln133_fu_536_p1) + $signed(sext_ln133_1_fu_540_p1));

assign add_ln313_fu_647_p2 = (pX_2 + 32'd1);

assign add_ln317_fu_694_p2 = (pY_2 + 32'd1);

assign add_ln323_fu_712_p2 = (sY_2 + 32'd1);

assign add_ln328_fu_664_p2 = (sX_2 + 32'd1);

assign add_ln51_fu_331_p2 = (indvar_flatten20_reg_187 + 13'd1);

assign and_ln289_1_fu_375_p2 = (grp_fu_307_p2 & and_ln289_fu_369_p2);

assign and_ln289_fu_369_p2 = (icmp_ln289_5_fu_363_p2 & icmp_ln289_4_fu_347_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op87_write_state7 == 1'b1));
end

always @ (*) begin
    ap_condition_329 = ((icmp_ln313_fu_652_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op87_write_state7 = ((1'd1 == and_ln289_1_reg_761) & (icmp_ln289_reg_748 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign grp_fu_307_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_484_p2 = ((ap_phi_mux_ir18_phi_fu_214_p4 == 6'd35) ? 1'b1 : 1'b0);

assign icmp_ln133_1_fu_554_p2 = ((out_index_reg_839 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln133_2_fu_559_p2 = ((out_index_reg_839 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln133_3_fu_564_p2 = ((add_ln133_fu_543_p2 != 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_549_p2 = ((out_index_reg_839 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_464_p2 = ((in_index_1_fu_458_p2 > 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln289_4_fu_347_p2 = (($signed(tmp_fu_337_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_5_fu_363_p2 = (($signed(tmp_26_fu_353_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_321_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_652_p2 = ((add_ln313_fu_647_p2 == 32'd66) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_700_p2 = ((add_ln317_fu_694_p2 == 32'd66) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_739_p2 = ((indvar_flatten20_reg_187 == 13'd4355) ? 1'b1 : 1'b0);

assign in_index_1_fu_458_p2 = (ap_phi_mux_in_index19_phi_fu_203_p4 + 4'd1);

assign in_index_fu_470_p3 = ((icmp_ln141_fu_464_p2[0:0] == 1'b1) ? 4'd0 : in_index_1_fu_458_p2);

assign ir_fu_478_p2 = (ap_phi_mux_ir18_phi_fu_214_p4 + 6'd1);

assign layer2_out_din = {{{{acc_8_reg_852}, {acc_7_reg_858}}, {acc_6_reg_864}}, {acc_reg_870}};

assign mul_ln73_fu_497_p1 = mul_ln73_fu_497_p10;

assign mul_ln73_fu_497_p10 = a_reg_815;

assign or_ln133_1_fu_570_p2 = (icmp_ln133_2_fu_559_p2 | icmp_ln133_1_fu_554_p2);

assign or_ln133_2_fu_582_p2 = (or_ln133_fu_576_p2 | icmp_ln133_3_fu_564_p2);

assign or_ln133_3_fu_600_p2 = (or_ln133_1_fu_570_p2 | icmp_ln133_fu_549_p2);

assign or_ln133_fu_576_p2 = (or_ln133_1_fu_570_p2 | icmp_ln133_fu_549_p2);

assign outidx_i_i_i_i_address0 = zext_ln124_fu_417_p1;

assign select_ln323_fu_718_p3 = ((grp_fu_307_p2[0:0] == 1'b1) ? 32'd2 : add_ln323_fu_712_p2);

assign select_ln328_fu_669_p3 = ((icmp_ln289_reg_748[0:0] == 1'b1) ? 32'd2 : add_ln328_fu_664_p2);

assign sext_ln133_1_fu_540_p1 = $signed(trunc_ln_reg_847);

assign sext_ln133_fu_536_p1 = $signed(tmp_s_fu_513_p11);

assign start_out = real_start;

assign tmp_26_fu_353_p4 = {{pX_2[31:1]}};

assign tmp_fu_337_p4 = {{pY_2[31:1]}};

assign tmp_s_fu_513_p9 = 'bx;

assign w2_address0 = zext_ln124_fu_417_p1;

assign zext_ln124_fu_417_p1 = ap_phi_mux_ir18_phi_fu_214_p4;

endmodule //myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_fixed_16_6_5_3_0_4u_config2_s
