// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_1u_array_ap_ufixed_8_0_4_0_0_1u_relu_config16_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer14_out_dout,
        layer14_out_empty_n,
        layer14_out_read,
        layer14_out_num_data_valid,
        layer14_out_fifo_cap,
        layer16_out_TREADY,
        layer16_out_TDATA,
        layer16_out_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] layer14_out_dout;
input   layer14_out_empty_n;
output   layer14_out_read;
input  [12:0] layer14_out_num_data_valid;
input  [12:0] layer14_out_fifo_cap;
input   layer16_out_TREADY;
output  [7:0] layer16_out_TDATA;
output   layer16_out_TVALID;

reg ap_idle;
reg layer14_out_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
wire    regslice_both_layer16_out_U_apdone_blk;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire   [0:0] icmp_ln41_fu_263_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    layer14_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    layer16_out_TDATA_blk_n;
wire   [7:0] out_data_4_fu_249_p3;
reg   [7:0] out_data_4_reg_281;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [11:0] i1_fu_68;
wire   [11:0] i_fu_257_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_i1_load;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] tmp_23_fu_137_p3;
wire   [0:0] trunc_ln52_fu_125_p1;
wire   [0:0] or_ln52_fu_145_p2;
wire   [0:0] tmp_21_fu_117_p3;
wire   [0:0] and_ln52_fu_151_p2;
wire   [7:0] trunc_ln_fu_107_p4;
wire   [7:0] zext_ln52_fu_157_p1;
wire   [5:0] tmp_s_fu_167_p3;
wire   [7:0] add_ln52_fu_161_p2;
wire   [0:0] tmp_22_fu_129_p3;
wire   [0:0] tmp_24_fu_181_p3;
wire   [0:0] not_tmp_29_fu_189_p2;
wire   [0:0] icmp_ln52_fu_175_p2;
wire   [0:0] and_ln52_8_fu_195_p2;
wire   [0:0] empty_fu_201_p2;
wire   [0:0] tmp_fu_99_p3;
wire   [0:0] xor_ln52_fu_213_p2;
wire   [0:0] or_ln52_8_fu_207_p2;
wire   [7:0] select_ln52_fu_225_p3;
wire   [0:0] or_ln52_9_fu_219_p2;
wire   [7:0] select_ln52_12_fu_233_p3;
wire   [0:0] icmp_ln51_fu_93_p2;
wire   [7:0] out_data_fu_241_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    layer16_out_TVALID_int_regslice;
wire    layer16_out_TREADY_int_regslice;
wire    regslice_both_layer16_out_U_vld_out;
reg    ap_condition_135;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 i1_fu_68 = 12'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

myproject_regslice_both #(
    .DataWidth( 8 ))
regslice_both_layer16_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_data_4_reg_281),
    .vld_in(layer16_out_TVALID_int_regslice),
    .ack_in(layer16_out_TREADY_int_regslice),
    .data_out(layer16_out_TDATA),
    .vld_out(regslice_both_layer16_out_U_vld_out),
    .ack_out(layer16_out_TREADY),
    .apdone_blk(regslice_both_layer16_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
    end else begin
        if ((ap_start_int == 1'b1)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_135)) begin
        i1_fu_68 <= i_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_4_reg_281 <= out_data_4_fu_249_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_263_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i1_load = 12'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer14_out_blk_n = layer14_out_empty_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer14_out_read = 1'b1;
    end else begin
        layer14_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        layer16_out_TDATA_blk_n = layer16_out_TREADY_int_regslice;
    end else begin
        layer16_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer16_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer16_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_161_p2 = (trunc_ln_fu_107_p4 + zext_ln52_fu_157_p1);

assign and_ln52_8_fu_195_p2 = (tmp_24_fu_181_p3 | not_tmp_29_fu_189_p2);

assign and_ln52_fu_151_p2 = (tmp_21_fu_117_p3 & or_ln52_fu_145_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_layer16_out_U_apdone_blk == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_layer16_out_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_layer16_out_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0)))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_layer16_out_U_apdone_blk == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_layer16_out_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_layer16_out_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0)))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_layer16_out_U_apdone_blk == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (layer16_out_TREADY_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (layer14_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_135 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_201_p2 = (icmp_ln52_fu_175_p2 & and_ln52_8_fu_195_p2);

assign i_fu_257_p2 = (ap_sig_allocacmp_i1_load + 12'd1);

assign icmp_ln41_fu_263_p2 = ((ap_sig_allocacmp_i1_load == 12'd4095) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_93_p2 = (($signed(layer14_out_dout) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_175_p2 = ((tmp_s_fu_167_p3 == 6'd0) ? 1'b1 : 1'b0);

assign layer16_out_TVALID = regslice_both_layer16_out_U_vld_out;

assign not_tmp_29_fu_189_p2 = (tmp_22_fu_129_p3 ^ 1'd1);

assign or_ln52_8_fu_207_p2 = (tmp_fu_99_p3 | empty_fu_201_p2);

assign or_ln52_9_fu_219_p2 = (xor_ln52_fu_213_p2 | tmp_fu_99_p3);

assign or_ln52_fu_145_p2 = (trunc_ln52_fu_125_p1 | tmp_23_fu_137_p3);

assign out_data_4_fu_249_p3 = ((icmp_ln51_fu_93_p2[0:0] == 1'b1) ? out_data_fu_241_p3 : 8'd0);

assign out_data_fu_241_p3 = ((or_ln52_9_fu_219_p2[0:0] == 1'b1) ? select_ln52_12_fu_233_p3 : add_ln52_fu_161_p2);

assign select_ln52_12_fu_233_p3 = ((or_ln52_8_fu_207_p2[0:0] == 1'b1) ? select_ln52_fu_225_p3 : 8'd255);

assign select_ln52_fu_225_p3 = ((tmp_fu_99_p3[0:0] == 1'b1) ? 8'd0 : add_ln52_fu_161_p2);

assign tmp_21_fu_117_p3 = layer14_out_dout[32'd1];

assign tmp_22_fu_129_p3 = layer14_out_dout[32'd9];

assign tmp_23_fu_137_p3 = layer14_out_dout[32'd2];

assign tmp_24_fu_181_p3 = add_ln52_fu_161_p2[32'd7];

assign tmp_fu_99_p3 = layer14_out_dout[32'd15];

assign tmp_s_fu_167_p3 = {{layer14_out_dout[15:10]}};

assign trunc_ln52_fu_125_p1 = layer14_out_dout[0:0];

assign trunc_ln_fu_107_p4 = {{layer14_out_dout[9:2]}};

assign xor_ln52_fu_213_p2 = (empty_fu_201_p2 ^ 1'd1);

assign zext_ln52_fu_157_p1 = and_ln52_fu_151_p2;

endmodule //myproject_relu_array_ap_fixed_1u_array_ap_ufixed_8_0_4_0_0_1u_relu_config16_s
