// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V3 Display

#ifndef _V3_DISPLAY_UI_H
#define _V3_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_new_nexswap_logo_big_png);    // assets/new nexswap logo big.png
LV_IMG_DECLARE(ui_img_nexswap_2_png);    // assets/nexswap_2.png
LV_IMG_DECLARE(ui_img_ellipsis_png);    // assets/ellipsis.png
LV_IMG_DECLARE(ui_img_asset_5_png);    // assets/Asset 5.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
