-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity myproject_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_8_4_5_3_0_4u_config10_s_w10_ROM_AGfk is 
    generic(
             DataWidth     : integer := 4; 
             AddressWidth     : integer := 8; 
             AddressRange    : integer := 144
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of myproject_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_8_4_5_3_0_4u_config10_s_w10_ROM_AGfk is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111", 1 => "0010", 2 => "1111", 3 => "0001", 
    4 => "1110", 5 => "1111", 6 => "0010", 7 => "1110", 
    8 => "0001", 9 => "0000", 10 => "1110", 11 => "0010", 
    12 => "1110", 13 => "1111", 14 => "1100", 15 => "0001", 
    16 => "1111", 17 => "0000", 18 => "0000", 19 => "1111", 
    20 => "0000", 21 => "0010", 22 => "1101", 23 => "0010", 
    24 => "1110", 25 => "0000", 26 => "0001", 27 => "0001", 
    28 => "0000", 29 => "0010", 30 => "1111", 31 => "0101", 
    32 => "0011", 33 => "0000", 34 => "1111", 35 => "0001", 
    36 => "1111", 37 => "0000", 38 => "0000", 39 => "1111", 
    40 => "0001", 41 => "1110", 42 => "1111", 43 => "0000", 
    44 => "1100", 45 => "0000", 46 => "1110", 47 => "0001", 
    48 => "0000", 49 => "1111", 50 => "0010", 51 => "0000", 
    52 => "0000", 53 => "0000", 54 => "0001", 55 => "0001", 
    56 => "1111", 57 => "0000", 58 => "1111", 59 => "0000", 
    60 => "1111", 61 => "1110", 62 => "0000", 63 => "0000", 
    64 => "1111", 65 => "0001", 66 => "1111", 67 => "0001", 
    68 => "0010", 69 => "0000", 70 => "1111", 71 => "0001", 
    72 => "0001", 73 => "0000", 74 => "1111", 75 => "1101", 
    76 => "0000", 77 => "0010", 78 => "0000", 79 => "0001", 
    80 => "0010", 81 => "1110", 82 => "0001", 83 => "1111", 
    84 => "1110", 85 => "0010", 86 => "1111", 87 => "1110", 
    88 => "1101", 89 => "0001", 90 => "1101", 91 => "0100", 
    92 => "1110", 93 => "0001", 94 => "0000", 95 => "1111", 
    96 => "0000", 97 => "0010", 98 => "1110", 99 => "1110", 
    100 => "1110", 101 => "0011", 102 => "0000", 103 => "1111", 
    104 => "0001", 105 => "1111", 106 => "1110", 107 => "0000", 
    108 => "0001", 109 => "1111", 110 => "1111", 111 => "0001", 
    112 => "0011", 113 => "1111", 114 => "0001", 115 => "0001", 
    116 => "1101", 117 => "1111", 118 => "0000", 119 => "0000", 
    120 => "0000", 121 => "1101", 122 => "1111", 123 => "0000", 
    124 => "1111", 125 => "1111", 126 => "0010", 127 => "1111", 
    128 => "0100", 129 => "0010", 130 => "0000", 131 => "0010", 
    132 => "0010", 133 => "1110", 134 => "1111", 135 => "1111", 
    136 => "0001", 137 => "1110", 138 => "0000", 139 => "1110", 
    140 => "1110", 141 => "1011", 142 => "0000", 143 => "1100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

