// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.3.0
// Project name: Audio Anomaly Monitor

#include "../ui.h"
#include <string.h>

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_StatusLabel = NULL;
lv_obj_t * ui_UptimeLabel = NULL;
lv_obj_t * ui_FpgaStateLabel = NULL;
static lv_obj_t * ui_TabView2 = NULL;
static lv_obj_t * ui_TabPage1 = NULL;
static lv_obj_t * ui_TabPage2 = NULL;
static lv_obj_t * ui_TabPage3 = NULL;
static lv_obj_t * ui_TabPage4 = NULL;
static lv_obj_t * ui_PanelTelemetry = NULL;
static lv_obj_t * ui_TextAreaRawData1 = NULL;
static lv_obj_t * ui_TextAreaRawData2 = NULL;

static void ui_append_textarea_line(lv_obj_t * ta, const char * text)
{
    if(ta == NULL || text == NULL) return;

    lv_textarea_add_text(ta, text);
    lv_textarea_add_text(ta, "\n");

    // Keep monitor responsive by trimming old log text.
    const uint32_t max_chars = 4096;
    const char * current = lv_textarea_get_text(ta);
    if(current != NULL) {
        size_t len = strlen(current);
        if(len > max_chars) {
            lv_textarea_set_text(ta, current + (len - max_chars));
        }
    }

    lv_textarea_set_cursor_pos(ta, LV_TEXTAREA_CURSOR_LAST);
    lv_obj_scroll_to_y(ta, LV_COORD_MAX, LV_ANIM_OFF);
}

void ui_append_uart0_monitor_line(const char * text)
{
    ui_append_textarea_line(ui_TextAreaRawData1, text);
}

void ui_append_uart2_monitor_line(const char * text)
{
    ui_append_textarea_line(ui_TextAreaRawData2, text);
}

void ui_set_uart2_monitor_text(const char * text)
{
    if(ui_TextAreaRawData2 == NULL || text == NULL) return;
    lv_textarea_set_text(ui_TextAreaRawData2, text);
    lv_textarea_set_cursor_pos(ui_TextAreaRawData2, LV_TEXTAREA_CURSOR_LAST);
    lv_obj_scroll_to_y(ui_TextAreaRawData2, LV_COORD_MAX, LV_ANIM_OFF);
}

static void ui_event_Button1_tabview_toggle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Keep tabview above telemetry widgets when shown.
        lv_obj_move_foreground(ui_TabView2);
        _ui_flag_modify(ui_TabView2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

static void ui_event_TelemetryPanel_open_spectrogram(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        lv_disp_load_scr(ui_Screen3);
    }
}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 480);
    lv_obj_set_height(ui_Panel2, 320);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 47);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -209);
    lv_obj_set_y(ui_Button1, -128);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_ellipsis_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_Screen2);
    lv_tabview_set_tab_bar_position(ui_TabView2, LV_DIR_LEFT);
    lv_tabview_set_tab_bar_size(ui_TabView2, 70);
    lv_obj_set_width(ui_TabView2, 394);
    lv_obj_set_height(ui_TabView2, 269);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TabView2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_anim_duration(ui_TabView2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_duration(lv_tabview_get_content(ui_TabView2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0x9A9A9A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "Setting");
    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "Raw Data 1");
    ui_TabPage3 = lv_tabview_add_tab(ui_TabView2, "Raw Data 2");
    ui_TabPage4 = lv_tabview_add_tab(ui_TabView2, "About");

    ui_TextAreaRawData1 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextAreaRawData1, lv_pct(100));
    lv_obj_set_height(ui_TextAreaRawData1, lv_pct(100));
    lv_obj_set_align(ui_TextAreaRawData1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaRawData1, "UART0 monitor...");
    lv_textarea_set_one_line(ui_TextAreaRawData1, false);
    lv_obj_remove_flag(ui_TextAreaRawData1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_text_font(ui_TextAreaRawData1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaRawData2 = lv_textarea_create(ui_TabPage3);
    lv_obj_set_width(ui_TextAreaRawData2, lv_pct(100));
    lv_obj_set_height(ui_TextAreaRawData2, lv_pct(100));
    lv_obj_set_align(ui_TextAreaRawData2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaRawData2, "UART2 monitor...");
    lv_textarea_set_one_line(ui_TextAreaRawData2, false);
    lv_obj_remove_flag(ui_TextAreaRawData2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_text_font(ui_TextAreaRawData2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Arc zone (left): uptime ring + anomaly dots rendered in runtime code.
    ui_Arc1 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1, 250);
    lv_obj_set_height(ui_Arc1, 250);
    lv_obj_set_x(ui_Arc1, -112);
    lv_obj_set_y(ui_Arc1, 0);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);
    lv_arc_set_bg_angles(ui_Arc1, 270, 269);
    lv_obj_set_style_arc_width(ui_Arc1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4D545B), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);

    // Telemetry zone (right): status + RMS bar + runtime metrics.
    ui_PanelTelemetry = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelTelemetry, 218);
    lv_obj_set_height(ui_PanelTelemetry, 292);
    lv_obj_set_x(ui_PanelTelemetry, 124);
    lv_obj_set_y(ui_PanelTelemetry, 0);
    lv_obj_set_align(ui_PanelTelemetry, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelTelemetry, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelTelemetry, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTelemetry, lv_color_hex(0x1D2228), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTelemetry, 235, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTelemetry, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTelemetry, lv_color_hex(0x39424D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_PanelTelemetry, ui_event_TelemetryPanel_open_spectrogram, LV_EVENT_CLICKED, NULL);

    // RMS bar inside telemetry panel.
    ui_Bar1 = lv_bar_create(ui_PanelTelemetry);
    lv_bar_set_range(ui_Bar1, 0, 255);
    lv_bar_set_value(ui_Bar1, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 18);
    lv_obj_set_height(ui_Bar1, 214);
    lv_obj_set_x(ui_Bar1, 88);
    lv_obj_set_y(ui_Bar1, -5);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xB81010), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0x20CF2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Bar1, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_Bar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);

    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_bottom(ui_Bar1,
                                                                                           lv_obj_get_style_pad_bottom(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);

    // Primary status and core metadata in telemetry panel.
    ui_StatusLabel = lv_label_create(ui_PanelTelemetry);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StatusLabel, -24);
    lv_obj_set_y(ui_StatusLabel, -108);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusLabel, "Normal");
    lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UptimeLabel = lv_label_create(ui_PanelTelemetry);
    lv_obj_set_width(ui_UptimeLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_UptimeLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_UptimeLabel, -20);
    lv_obj_set_y(ui_UptimeLabel, -72);
    lv_obj_set_align(ui_UptimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UptimeLabel, "uptime");
    lv_obj_set_style_text_color(ui_UptimeLabel, lv_color_hex(0xCAD1D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UptimeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FpgaStateLabel = lv_label_create(ui_PanelTelemetry);
    lv_obj_set_width(ui_FpgaStateLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_FpgaStateLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_FpgaStateLabel, -20);
    lv_obj_set_y(ui_FpgaStateLabel, -42);
    lv_obj_set_align(ui_FpgaStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FpgaStateLabel, "Active");
    lv_obj_set_style_text_font(ui_FpgaStateLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1_tabview_toggle, LV_EVENT_ALL, NULL);
}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel2 = NULL;
    ui_Image4 = NULL;
    ui_Button1 = NULL;
    ui_Arc1 = NULL;
    ui_Bar1 = NULL;
    ui_StatusLabel = NULL;
    ui_UptimeLabel = NULL;
    ui_FpgaStateLabel = NULL;
    ui_TabView2 = NULL;
    ui_TabPage1 = NULL;
    ui_TabPage2 = NULL;
    ui_TabPage3 = NULL;
    ui_TabPage4 = NULL;
    ui_PanelTelemetry = NULL;
    ui_TextAreaRawData1 = NULL;
    ui_TextAreaRawData2 = NULL;
}
