// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V3 Display
// Adapted for 480x320 display with touch screen and settings Tab

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern void ui_append_uart0_monitor_line(const char * text);
extern void ui_append_uart2_monitor_line(const char * text);
extern void ui_set_uart2_monitor_text(const char * text);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
