-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer8_out_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    layer8_out_empty_n : IN STD_LOGIC;
    layer8_out_read : OUT STD_LOGIC;
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer9_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    layer9_out_full_n : IN STD_LOGIC;
    layer9_out_write : OUT STD_LOGIC;
    layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln55_reg_907 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_reg_911 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op136_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal icmp_ln109_reg_903 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sY_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal pX_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sX_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal layer8_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal layer9_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal icmp_ln109_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln55_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_fu_405_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_reg_915 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_1_fu_513_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_1_reg_920 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_2_fu_621_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_2_reg_925 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_3_fu_729_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln65_3_reg_930 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln76_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_825_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_done : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_idle : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ready : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read1 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read2 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read3 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 : STD_LOGIC_VECTOR (5 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce : STD_LOGIC;
    signal ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp22 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp22_grp1 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_storemerge_i_reg_131 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_i_reg_131 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_ignoreCallOp22_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_ln80_fu_791_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln76_fu_737_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln91_fu_761_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten2_fu_114 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln109_fu_198_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_indvar_flatten2_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal icmp_ln55_2_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_3_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_1_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_309_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_s_fu_321_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_1_fu_333_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_2_fu_345_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_1_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_1_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_fu_365_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln0_1_fu_385_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_2_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_2_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_3_fu_417_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_4_fu_429_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_3_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_3_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_5_fu_441_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_6_fu_453_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_4_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_4_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_2_fu_473_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln0_3_fu_493_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_5_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_5_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_7_fu_525_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_8_fu_537_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_6_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_6_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_9_fu_549_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_10_fu_561_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_7_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_7_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_4_fu_581_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln0_5_fu_601_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_8_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_8_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_11_fu_633_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_12_fu_645_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_9_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_9_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln63_13_fu_657_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln63_14_fu_669_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_10_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_10_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_6_fu_689_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln0_7_fu_709_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln65_11_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_11_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln91_fu_755_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln86_fu_813_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln86_fu_819_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_pack_fu_839_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_pack_1_fu_850_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_pack_2_fu_861_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln48_2_fu_868_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln48_1_fu_857_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln48_fu_846_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln72_s_fu_872_p6 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_266 : BOOLEAN;
    signal ap_condition_252 : BOOLEAN;
    signal ap_condition_365 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_i : IN STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_i : IN STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_i : IN STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_i : IN STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_i : IN STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_i : IN STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 : OUT STD_LOGIC_VECTOR (5 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_i : IN STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_i : IN STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142 : component myproject_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start,
        ap_done => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_done,
        ap_idle => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_idle,
        ap_ready => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ready,
        p_read => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read,
        p_read1 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read1,
        p_read2 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read2,
        p_read3 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read3,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld,
        ap_ce => call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ready = ap_const_logic_1)) then 
                    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_storemerge_i_reg_131_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln80_fu_797_p2 = ap_const_lv1_1) and (icmp_ln76_fu_743_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_reg_131 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln80_fu_797_p2 = ap_const_lv1_0) and (icmp_ln76_fu_743_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_reg_131 <= select_ln86_fu_825_p3;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_reg_131 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_131;
            end if; 
        end if;
    end process;

    indvar_flatten2_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_266)) then
                indvar_flatten2_fu_114 <= add_ln109_fu_198_p2;
            end if;
        end if;
    end process;

    pX_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_252)) then
                if ((icmp_ln76_fu_743_p2 = ap_const_lv1_1)) then 
                    pX_1 <= ap_const_lv32_0;
                elsif ((icmp_ln76_fu_743_p2 = ap_const_lv1_0)) then 
                    pX_1 <= add_ln76_fu_737_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_365)) then
                if ((icmp_ln80_fu_797_p2 = ap_const_lv1_1)) then 
                    pY_1 <= ap_const_lv32_0;
                elsif ((icmp_ln80_fu_797_p2 = ap_const_lv1_0)) then 
                    pY_1 <= add_ln80_fu_791_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_252)) then
                if ((icmp_ln76_fu_743_p2 = ap_const_lv1_1)) then 
                    sX_1 <= ap_const_lv32_0;
                elsif ((icmp_ln76_fu_743_p2 = ap_const_lv1_0)) then 
                    sX_1 <= select_ln91_fu_761_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln55_1_reg_911 <= and_ln55_1_fu_299_p2;
                icmp_ln109_reg_903 <= icmp_ln109_fu_204_p2;
                icmp_ln55_reg_907 <= icmp_ln55_fu_257_p2;
                icmp_ln76_reg_935 <= icmp_ln76_fu_743_p2;
                    select_ln65_1_reg_920(8 downto 3) <= select_ln65_1_fu_513_p3(8 downto 3);
                    select_ln65_2_reg_925(8 downto 3) <= select_ln65_2_fu_621_p3(8 downto 3);
                    select_ln65_3_reg_930(8 downto 3) <= select_ln65_3_fu_729_p3(8 downto 3);
                    select_ln65_reg_915(8 downto 3) <= select_ln65_fu_405_p3(8 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_935 = ap_const_lv1_1))) then
                sY_1 <= ap_phi_reg_pp0_iter1_storemerge_i_reg_131;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19;
            end if;
        end if;
    end process;
    select_ln65_reg_915(2 downto 0) <= "000";
    select_ln65_1_reg_920(2 downto 0) <= "000";
    select_ln65_2_reg_925(2 downto 0) <= "000";
    select_ln65_3_reg_930(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln109_fu_198_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten2_load) + unsigned(ap_const_lv10_1));
    add_ln76_fu_737_p2 <= std_logic_vector(unsigned(pX_1) + unsigned(ap_const_lv32_1));
    add_ln80_fu_791_p2 <= std_logic_vector(unsigned(pY_1) + unsigned(ap_const_lv32_1));
    add_ln86_fu_819_p2 <= std_logic_vector(unsigned(sY_1) + unsigned(ap_const_lv32_1));
    add_ln91_fu_755_p2 <= std_logic_vector(unsigned(sX_1) + unsigned(ap_const_lv32_1));
    and_ln55_1_fu_299_p2 <= (icmp_ln55_1_fu_271_p2 and and_ln55_fu_293_p2);
    and_ln55_fu_293_p2 <= (icmp_ln55_3_fu_287_p2 and icmp_ln55_2_fu_281_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage1_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_01001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer8_out_empty_n = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp1_assign_proc : process(layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer8_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2));
    end process;


    ap_block_pp0_stage1_11001_ignoreCallOp22_assign_proc : process(ap_enable_reg_pp0_iter1, layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2)
    begin
                ap_block_pp0_stage1_11001_ignoreCallOp22 <= (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer8_out_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage1_11001_ignoreCallOp22_grp1_assign_proc : process(layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_ignoreCallOp22_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer8_out_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_ignoreCallOp22_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer8_out_empty_n = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp1_assign_proc : process(layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer8_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state4_pp0_stage1_iter1_grp2_assign_proc : process(layer9_out_full_n, ap_predicate_op136_write_state4)
    begin
                ap_block_state4_pp0_stage1_iter1_grp2 <= ((ap_predicate_op136_write_state4 = ap_const_boolean_1) and (layer9_out_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2_assign_proc : process(layer9_out_full_n, ap_predicate_op136_write_state4)
    begin
                ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2 <= ((ap_predicate_op136_write_state4 = ap_const_boolean_1) and (layer9_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_252_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_252 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_266_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_266 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_365_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln76_fu_743_p2)
    begin
                ap_condition_365 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_fu_743_p2 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln109_reg_903)
    begin
        if (((icmp_ln109_reg_903 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_phi_reg_pp0_iter0_storemerge_i_reg_131 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op136_write_state4_assign_proc : process(icmp_ln55_reg_907, and_ln55_1_reg_911)
    begin
                ap_predicate_op136_write_state4 <= ((ap_const_lv1_1 = and_ln55_1_reg_911) and (icmp_ln55_reg_907 = ap_const_lv1_1));
    end process;

    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, indvar_flatten2_fu_114, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten2_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten2_load <= indvar_flatten2_fu_114;
        end if; 
    end process;


    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_pp0_stage1_11001_ignoreCallOp22_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp22_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce <= ap_const_logic_1;
        else 
            call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start <= call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_ap_start_reg;
    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read <= layer8_out_dout(6 - 1 downto 0);
    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read1 <= layer8_out_dout(11 downto 6);
    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read2 <= layer8_out_dout(17 downto 12);
    call_ln52_shift_line_buffer_array_ap_ufixed_6_1_5_3_0_4u_config9_s_fu_142_p_read3 <= layer8_out_dout(23 downto 18);
    icmp_ln109_fu_204_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten2_load = ap_const_lv10_3FF) else "0";
    icmp_ln55_1_fu_271_p2 <= "1" when (sY_1 = ap_const_lv32_1) else "0";
    icmp_ln55_2_fu_281_p2 <= "1" when (signed(pY_1) > signed(ap_const_lv32_0)) else "0";
    icmp_ln55_3_fu_287_p2 <= "1" when (signed(pX_1) > signed(ap_const_lv32_0)) else "0";
    icmp_ln55_fu_257_p2 <= "1" when (sX_1 = ap_const_lv32_1) else "0";
    icmp_ln65_10_fu_697_p2 <= "1" when (unsigned(shl_ln63_13_fu_657_p3) < unsigned(shl_ln63_14_fu_669_p3)) else "0";
    icmp_ln65_11_fu_717_p2 <= "1" when (unsigned(select_ln0_6_fu_689_p3) < unsigned(select_ln0_7_fu_709_p3)) else "0";
    icmp_ln65_1_fu_373_p2 <= "1" when (unsigned(shl_ln63_1_fu_333_p3) < unsigned(shl_ln63_2_fu_345_p3)) else "0";
    icmp_ln65_2_fu_393_p2 <= "1" when (unsigned(select_ln0_fu_365_p3) < unsigned(select_ln0_1_fu_385_p3)) else "0";
    icmp_ln65_3_fu_461_p2 <= "1" when (unsigned(shl_ln63_3_fu_417_p3) < unsigned(shl_ln63_4_fu_429_p3)) else "0";
    icmp_ln65_4_fu_481_p2 <= "1" when (unsigned(shl_ln63_5_fu_441_p3) < unsigned(shl_ln63_6_fu_453_p3)) else "0";
    icmp_ln65_5_fu_501_p2 <= "1" when (unsigned(select_ln0_2_fu_473_p3) < unsigned(select_ln0_3_fu_493_p3)) else "0";
    icmp_ln65_6_fu_569_p2 <= "1" when (unsigned(shl_ln63_7_fu_525_p3) < unsigned(shl_ln63_8_fu_537_p3)) else "0";
    icmp_ln65_7_fu_589_p2 <= "1" when (unsigned(shl_ln63_9_fu_549_p3) < unsigned(shl_ln63_10_fu_561_p3)) else "0";
    icmp_ln65_8_fu_609_p2 <= "1" when (unsigned(select_ln0_4_fu_581_p3) < unsigned(select_ln0_5_fu_601_p3)) else "0";
    icmp_ln65_9_fu_677_p2 <= "1" when (unsigned(shl_ln63_11_fu_633_p3) < unsigned(shl_ln63_12_fu_645_p3)) else "0";
    icmp_ln65_fu_353_p2 <= "1" when (unsigned(shl_ln_fu_309_p3) < unsigned(shl_ln63_s_fu_321_p3)) else "0";
    icmp_ln76_fu_743_p2 <= "1" when (add_ln76_fu_737_p2 = ap_const_lv32_20) else "0";
    icmp_ln80_fu_797_p2 <= "1" when (add_ln80_fu_791_p2 = ap_const_lv32_20) else "0";
    icmp_ln86_fu_813_p2 <= "1" when (sY_1 = ap_const_lv32_1) else "0";

    layer8_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage1, layer8_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_grp1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer8_out_blk_n <= layer8_out_empty_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer8_out_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer8_out_read <= ap_const_logic_1;
        else 
            layer8_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer9_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, layer9_out_full_n, ap_predicate_op136_write_state4, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_grp2)
    begin
        if (((ap_predicate_op136_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer9_out_blk_n <= layer9_out_full_n;
        else 
            layer9_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer9_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln72_s_fu_872_p6),64));

    layer9_out_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op136_write_state4, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_11001_grp2)
    begin
        if (((ap_predicate_op136_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer9_out_write <= ap_const_logic_1;
        else 
            layer9_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln72_s_fu_872_p6 <= ((((select_ln65_3_reg_930 & ap_const_lv2_0) & zext_ln48_2_fu_868_p1) & zext_ln48_1_fu_857_p1) & zext_ln48_fu_846_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    res_pack_1_fu_850_p3 <= (select_ln65_1_reg_920 & ap_const_lv2_0);
    res_pack_2_fu_861_p3 <= (select_ln65_2_reg_925 & ap_const_lv2_0);
    res_pack_fu_839_p3 <= (select_ln65_reg_915 & ap_const_lv2_0);
    select_ln0_1_fu_385_p3 <= 
        shl_ln63_1_fu_333_p3 when (xor_ln65_1_fu_379_p2(0) = '1') else 
        shl_ln63_2_fu_345_p3;
    select_ln0_2_fu_473_p3 <= 
        shl_ln63_3_fu_417_p3 when (xor_ln65_3_fu_467_p2(0) = '1') else 
        shl_ln63_4_fu_429_p3;
    select_ln0_3_fu_493_p3 <= 
        shl_ln63_5_fu_441_p3 when (xor_ln65_4_fu_487_p2(0) = '1') else 
        shl_ln63_6_fu_453_p3;
    select_ln0_4_fu_581_p3 <= 
        shl_ln63_7_fu_525_p3 when (xor_ln65_6_fu_575_p2(0) = '1') else 
        shl_ln63_8_fu_537_p3;
    select_ln0_5_fu_601_p3 <= 
        shl_ln63_9_fu_549_p3 when (xor_ln65_7_fu_595_p2(0) = '1') else 
        shl_ln63_10_fu_561_p3;
    select_ln0_6_fu_689_p3 <= 
        shl_ln63_11_fu_633_p3 when (xor_ln65_9_fu_683_p2(0) = '1') else 
        shl_ln63_12_fu_645_p3;
    select_ln0_7_fu_709_p3 <= 
        shl_ln63_13_fu_657_p3 when (xor_ln65_10_fu_703_p2(0) = '1') else 
        shl_ln63_14_fu_669_p3;
    select_ln0_fu_365_p3 <= 
        shl_ln_fu_309_p3 when (xor_ln65_fu_359_p2(0) = '1') else 
        shl_ln63_s_fu_321_p3;
    select_ln65_1_fu_513_p3 <= 
        select_ln0_2_fu_473_p3 when (xor_ln65_5_fu_507_p2(0) = '1') else 
        select_ln0_3_fu_493_p3;
    select_ln65_2_fu_621_p3 <= 
        select_ln0_4_fu_581_p3 when (xor_ln65_8_fu_615_p2(0) = '1') else 
        select_ln0_5_fu_601_p3;
    select_ln65_3_fu_729_p3 <= 
        select_ln0_6_fu_689_p3 when (xor_ln65_11_fu_723_p2(0) = '1') else 
        select_ln0_7_fu_709_p3;
    select_ln65_fu_405_p3 <= 
        select_ln0_fu_365_p3 when (xor_ln65_2_fu_399_p2(0) = '1') else 
        select_ln0_1_fu_385_p3;
    select_ln86_fu_825_p3 <= 
        ap_const_lv32_0 when (icmp_ln86_fu_813_p2(0) = '1') else 
        add_ln86_fu_819_p2;
    select_ln91_fu_761_p3 <= 
        ap_const_lv32_0 when (icmp_ln55_fu_257_p2(0) = '1') else 
        add_ln91_fu_755_p2;
    shl_ln63_10_fu_561_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_1 & ap_const_lv3_0);
    shl_ln63_11_fu_633_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_16 & ap_const_lv3_0);
    shl_ln63_12_fu_645_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_12 & ap_const_lv3_0);
    shl_ln63_13_fu_657_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_4 & ap_const_lv3_0);
    shl_ln63_14_fu_669_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap & ap_const_lv3_0);
    shl_ln63_1_fu_333_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_11 & ap_const_lv3_0);
    shl_ln63_2_fu_345_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_3 & ap_const_lv3_0);
    shl_ln63_3_fu_417_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_18 & ap_const_lv3_0);
    shl_ln63_4_fu_429_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_14 & ap_const_lv3_0);
    shl_ln63_5_fu_441_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_10 & ap_const_lv3_0);
    shl_ln63_6_fu_453_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_2 & ap_const_lv3_0);
    shl_ln63_7_fu_525_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_17 & ap_const_lv3_0);
    shl_ln63_8_fu_537_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_13 & ap_const_lv3_0);
    shl_ln63_9_fu_549_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi1EL9ap_q_mode5EL9ap_5 & ap_const_lv3_0);
    shl_ln63_s_fu_321_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_15 & ap_const_lv3_0);
    shl_ln_fu_309_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_19 & ap_const_lv3_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln65_10_fu_703_p2 <= (icmp_ln65_10_fu_697_p2 xor ap_const_lv1_1);
    xor_ln65_11_fu_723_p2 <= (icmp_ln65_11_fu_717_p2 xor ap_const_lv1_1);
    xor_ln65_1_fu_379_p2 <= (icmp_ln65_1_fu_373_p2 xor ap_const_lv1_1);
    xor_ln65_2_fu_399_p2 <= (icmp_ln65_2_fu_393_p2 xor ap_const_lv1_1);
    xor_ln65_3_fu_467_p2 <= (icmp_ln65_3_fu_461_p2 xor ap_const_lv1_1);
    xor_ln65_4_fu_487_p2 <= (icmp_ln65_4_fu_481_p2 xor ap_const_lv1_1);
    xor_ln65_5_fu_507_p2 <= (icmp_ln65_5_fu_501_p2 xor ap_const_lv1_1);
    xor_ln65_6_fu_575_p2 <= (icmp_ln65_6_fu_569_p2 xor ap_const_lv1_1);
    xor_ln65_7_fu_595_p2 <= (icmp_ln65_7_fu_589_p2 xor ap_const_lv1_1);
    xor_ln65_8_fu_615_p2 <= (icmp_ln65_8_fu_609_p2 xor ap_const_lv1_1);
    xor_ln65_9_fu_683_p2 <= (icmp_ln65_9_fu_677_p2 xor ap_const_lv1_1);
    xor_ln65_fu_359_p2 <= (icmp_ln65_fu_353_p2 xor ap_const_lv1_1);
    zext_ln48_1_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_pack_1_fu_850_p3),16));
    zext_ln48_2_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_pack_2_fu_861_p3),16));
    zext_ln48_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_pack_fu_839_p3),16));
end behav;
