// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_fixed_16_6_5_3_0_4u_config2_s_outidx_idEe (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 2;
parameter AddressWidth = 6;
parameter AddressRange = 36;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_fixed_16_6_5_3_0_4u_config2_s_outidx_idEe.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

