// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: DSL_FFT_Project
// Adapted for 480x320 display with touch screen

#ifndef _DSL_FFT_PROJECT_UI_H
#define _DSL_FFT_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;

// SCREEN: ui_Screen2
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_UptimeLabel;
extern lv_obj_t * ui_FpgaStateLabel;
void ui_append_uart0_monitor_line(const char * text);
void ui_append_uart2_monitor_line(const char * text);
void ui_set_uart2_monitor_text(const char * text);

// SCREEN: ui_Screen3
extern lv_obj_t * ui_Screen3;

// IMAGE ASSETS
LV_IMG_DECLARE(ui_img_new_nexswap_logo_big_png);    // assets/new nexswap logo big.png
LV_IMG_DECLARE(ui_img_nexswap_2_png);    // assets/nexswap_2.png
LV_IMG_DECLARE(ui_img_ellipsis_png);    // assets/ellipsis.png
LV_IMG_DECLARE(ui_img_asset_5_png);    // assets/Asset 5.png

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
